// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzODHprkHmbN98S6zP_rvsMNXw3FWgHUM',
    appId: '1:150511120502:web:98512e237ed902d5c72f57',
    messagingSenderId: '150511120502',
    projectId: 'final-year-335b1',
    authDomain: 'final-year-335b1.firebaseapp.com',
    storageBucket: 'final-year-335b1.firebasestorage.app',
    measurementId: 'G-B5ZGDJ845J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJw60YdbLduU_snT77ZdpxGy9F5jJJmsI',
    appId: '1:150511120502:android:d7f0235a5a1dc17dc72f57',
    messagingSenderId: '150511120502',
    projectId: 'final-year-335b1',
    storageBucket: 'final-year-335b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bXzKSDYtl5DObRR61gFcqp5PzJdniAA',
    appId: '1:150511120502:ios:16095bb9f859898ec72f57',
    messagingSenderId: '150511120502',
    projectId: 'final-year-335b1',
    storageBucket: 'final-year-335b1.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-bXzKSDYtl5DObRR61gFcqp5PzJdniAA',
    appId: '1:150511120502:ios:16095bb9f859898ec72f57',
    messagingSenderId: '150511120502',
    projectId: 'final-year-335b1',
    storageBucket: 'final-year-335b1.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzODHprkHmbN98S6zP_rvsMNXw3FWgHUM',
    appId: '1:150511120502:web:9077d2efb1740392c72f57',
    messagingSenderId: '150511120502',
    projectId: 'final-year-335b1',
    authDomain: 'final-year-335b1.firebaseapp.com',
    storageBucket: 'final-year-335b1.firebasestorage.app',
    measurementId: 'G-VSK5GE58EP',
  );
}
